services:
  postgres:
    image: postgres:16-alpine
    container_name: my-market-postgres
    environment:
      POSTGRES_DB: my_market_app
      POSTGRES_USER: my_market_user
      POSTGRES_PASSWORD: my_market_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_market_user -d my_market_app"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-market-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
      payment:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/my_market_app
      SPRING_DATASOURCE_USERNAME: my_market_user
      SPRING_DATASOURCE_PASSWORD: my_market_password
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/my_market_app
      SPRING_R2DBC_USERNAME: my_market_user
      SPRING_R2DBC_PASSWORD: my_market_password
      SERVER_PORT: 8080
      PAYMENT_SERVICE_BASE_URL: http://payment:8081
      SPRING_DATA_REDIS_HOST: redis
      KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/my-market/protocol/openid-connect/token
      PAYMENT_OAUTH2_CLIENT_ID: my-market-app-client
      PAYMENT_OAUTH2_CLIENT_SECRET: my-market-app-client-secret
    ports:
      - "8080:8080"

  payment:
    build:
      context: .
      dockerfile: Dockerfile.payment
    container_name: my-market-payment
    depends_on:
      keycloak:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      PAYMENT_INITIAL_BALANCE: "10000.00"
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/my-market
    ports:
      - "8081:8081"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: my-market-keycloak
    command: ["start-dev", "--http-port=8080", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    volumes:
      - ./infra/keycloak/my-market-realm.json:/opt/keycloak/data/import/my-market-realm.json:ro

  redis:
    image: redis:7-alpine
    container_name: my-market-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
