FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /build

COPY . .
RUN ./mvnw -B clean package -pl my-market-payment -am -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=builder /build/my-market-payment/target/my-market-payment-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENV SERVER_PORT=8081

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
